// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhrsgmjuarysfxaoimty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhocnNnbWp1YXJ5c2Z4YW9pbXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTgxMDQsImV4cCI6MjA2NTU3NDEwNH0.dIMRdtIG-HIS_muAosOOytXMGiequgB-DLPPYOGr7kc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);